# Generated by Django 3.0.5 on 2020-05-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='message',
        ),
    ]
