# Generated by Django 3.0.5 on 2020-05-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0002_remove_emergencycontact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
