# Generated by Django 3.0.5 on 2020-05-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0003_auto_20200503_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesandregulations',
            name='rule',
            field=models.TextField(default='Insert Rules Here.', unique=True),
        ),
    ]
