# Generated by Django 3.0.5 on 2020-05-03 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0004_rulesandregulations_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesandregulations',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 12, 11, 4, 80090, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
