# Generated by Django 3.0.5 on 2020-05-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0005_rulesandregulations_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesandregulations',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date Published'),
        ),
    ]
