# Generated by Django 3.0.5 on 2020-05-03 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0006_auto_20200503_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionschedule',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 12, 28, 0, 923197, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='missionschedule',
            name='mission_details',
            field=models.CharField(default='Insert Mission Details Here.', max_length=200),
        ),
        migrations.AddField(
            model_name='missionschedule',
            name='mission_title',
            field=models.CharField(default='Insert Mission Title Here.', max_length=200),
        ),
        migrations.AddField(
            model_name='missionschedule',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 12, 28, 0, 923182, tzinfo=utc), verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='rulesandregulations',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date Added'),
        ),
    ]
