# Generated by Django 3.0.5 on 2020-05-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0007_auto_20200503_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionschedule',
            name='end_date',
            field=models.DateTimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='missionschedule',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
    ]
