# Generated by Django 3.0.5 on 2020-05-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0008_auto_20200503_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missionschedule',
            old_name='mission_details',
            new_name='mission_description',
        ),
    ]
