# Generated by Django 3.0.5 on 2020-05-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0009_auto_20200503_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missionschedule',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='missionschedule',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
