# Generated by Django 3.0.5 on 2020-05-03 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0010_auto_20200503_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='missionschedule',
            name='mission_description',
        ),
        migrations.RemoveField(
            model_name='missionschedule',
            name='mission_title',
        ),
        migrations.RemoveField(
            model_name='missionschedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='missiondetails',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missiondetails',
            name='mission_description',
            field=models.CharField(default='Insert Mission Details Here.', max_length=200),
        ),
        migrations.AddField(
            model_name='missiondetails',
            name='mission_title',
            field=models.CharField(default='Insert Mission Title Here.', max_length=200),
        ),
        migrations.AddField(
            model_name='missiondetails',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
            preserve_default=False,
        ),
    ]
