# Generated by Django 3.0.5 on 2020-05-03 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0011_auto_20200503_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesandregulations',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 12, 43, 8, 94450, tzinfo=utc), verbose_name='Date Added'),
        ),
    ]
