# Generated by Django 3.0.5 on 2020-05-03 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0012_auto_20200503_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesAndRegulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(default='Insert Rules Here.', unique=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 5, 3, 12, 44, 42, 935153, tzinfo=utc), verbose_name='Date Added')),
            ],
        ),
        migrations.RenameModel(
            old_name='MissionDetails',
            new_name='MissionDetail',
        ),
        migrations.DeleteModel(
            name='RulesAndRegulations',
        ),
    ]
