# Generated by Django 3.0.5 on 2020-05-03 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0013_auto_20200503_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesandregulation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 12, 44, 49, 344009, tzinfo=utc), verbose_name='Date Added'),
        ),
    ]
