# Generated by Django 3.0.5 on 2020-05-03 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0014_auto_20200503_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiondetail',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 13, 12, 40, 543497, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='missiondetail',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 13, 12, 40, 512346, tzinfo=utc), verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='rulesandregulation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 13, 12, 40, 543890, tzinfo=utc), verbose_name='Date Added'),
        ),
    ]
