# Generated by Django 3.0.5 on 2020-05-03 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0015_auto_20200503_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiondetail',
            name='end_time',
            field=models.DateTimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='missiondetail',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='rulesandregulation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 13, 15, 23, 626434, tzinfo=utc), verbose_name='Date Added'),
        ),
    ]
