# Generated by Django 3.0.5 on 2020-05-03 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0016_auto_20200503_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesandregulation',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
    ]
