# Generated by Django 3.0.5 on 2020-05-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0017_auto_20200503_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionSchedule',
        ),
    ]
