# Generated by Django 3.0.5 on 2020-05-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0018_delete_missionschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesandregulation',
            name='rule',
            field=models.CharField(default='Insert Rules Here.', max_length=200),
        ),
    ]
