# Generated by Django 3.0.5 on 2020-05-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0019_auto_20200505_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesandregulation',
            name='rule',
            field=models.TextField(default='Insert Rules Here.', unique=True),
        ),
    ]
