# Generated by Django 3.0.5 on 2020-05-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0020_auto_20200505_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionDetail',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
