# Generated by Django 3.0.5 on 2020-05-08 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_title_chi', models.CharField(default='输入任务主题', max_length=200)),
                ('mission_title_eng', models.CharField(default='Insert Mission Title here.', max_length=200)),
                ('mission_description_chi', models.TextField(default='输入任务资料')),
                ('mission_description_eng', models.TextField(default='Insert Mission Details Here.')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+60', max_length=128, region=None, unique=True)),
                ('satellite', models.CharField(choices=[('KL', 'Kuchai Lama'), ('PUC', 'Puchong'), ('STP', 'Setapak'), ('RW', 'Rawang'), ('PJ', 'Petaling Jaya'), ('USJ', 'UEP Subang Jaya'), ('KLG', 'Klang'), ('KP', 'Kepong'), ('SB', 'Seremban'), ('SD', 'Serdang'), ('KJ', 'Kajang'), ('SGL', 'Sungai Long')], max_length=200)),
                ('pastoral_team', models.CharField(max_length=200)),
                ('pastoral_cg', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
