# Generated by Django 3.0.5 on 2020-05-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='m1',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m2',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m3',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m4',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m5',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m6',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
    ]
