# Generated by Django 3.0.5 on 2020-05-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200514_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='m1',
            field=models.BooleanField(default=False, verbose_name='m1 completed'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='m2',
            field=models.BooleanField(default=False, verbose_name='m2 completed'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='m3',
            field=models.BooleanField(default=False, verbose_name='m3 completed'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='m4',
            field=models.BooleanField(default=False, verbose_name='m4 completed'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='m5',
            field=models.BooleanField(default=False, verbose_name='m5 completed'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='m6',
            field=models.BooleanField(default=False, verbose_name='m6 completed'),
        ),
    ]
