# Generated by Django 3.0.5 on 2020-05-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200514_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
