# Generated by Django 3.0.6 on 2020-05-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200514_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='m2_a',
            field=models.BooleanField(default=False, verbose_name='m2(guess song) completed'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m2_b',
            field=models.BooleanField(default=False, verbose_name='m2(translate song) completed'),
        ),
    ]
