# Generated by Django 3.0.6 on 2020-05-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200519_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='m2_a',
            field=models.BooleanField(default=False, verbose_name='m2_a(guess song) completed'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='m2_b',
            field=models.BooleanField(default=False, verbose_name='m2_b(translate song) completed'),
        ),
    ]
