# Generated by Django 3.0.6 on 2020-05-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200519_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='m2',
        ),
    ]
