# Generated by Django 3.0.6 on 2020-05-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_inspector_m2'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='m5_trials',
            field=models.IntegerField(default=10, verbose_name='m5 trials'),
        ),
    ]
