# Generated by Django 3.0.6 on 2020-05-20 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_inspector_m5_trials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='screenshots/')),
                ('inspector', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Inspector')),
            ],
        ),
    ]
