# Generated by Django 3.0.6 on 2020-05-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_screenshots'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screenshots',
            new_name='Screenshot',
        ),
    ]
