# Generated by Django 3.0.6 on 2020-05-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200520_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screenshot',
            new_name='QuanMinScreenshot',
        ),
    ]
