# Generated by Django 3.0.6 on 2020-05-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200520_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='quanminscreenshot',
            name='images_height',
            field=models.IntegerField(default=1920),
        ),
        migrations.AddField(
            model_name='quanminscreenshot',
            name='images_width',
            field=models.IntegerField(default=1080),
        ),
    ]
