# Generated by Django 3.0.6 on 2020-05-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200520_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quanminscreenshot',
            name='images_height',
        ),
        migrations.RemoveField(
            model_name='quanminscreenshot',
            name='images_width',
        ),
    ]
