# Generated by Django 3.0.6 on 2020-05-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200520_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='satellite',
            field=models.CharField(choices=[('KLMV', 'KL Move'), ('KLV', 'KL Voice'), ('KLH', 'KL Heart'), ('KLMD', 'KL Mind'), ('KLF', 'KL Force'), ('KLS', 'KL Strike'), ('PUC', 'Puchong'), ('STP', 'Setapak'), ('RW', 'Rawang'), ('PJ', 'Petaling Jaya'), ('USJ', 'USJ'), ('KLG', 'Klang'), ('KP', 'Kepong'), ('SB', 'Seremban'), ('SD', 'Serdang'), ('KJ', 'Kajang'), ('SGL', 'Sungai Long')], max_length=200),
        ),
    ]
