# Generated by Django 3.0.6 on 2020-05-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200521_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='m1_trials',
            field=models.IntegerField(default=10, verbose_name='m1 trials'),
        ),
    ]
