# Generated by Django 3.0.6 on 2020-05-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_inspector_m1_trials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='pastoral_cg',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='pastoral_team',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='inspector',
            name='m1_trials',
            field=models.IntegerField(default=15, verbose_name='m1 trials'),
        ),
    ]
