# Generated by Django 3.0.6 on 2020-05-23 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200522_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='m1_time_used',
            field=models.DurationField(default=datetime.timedelta(0, 3600), verbose_name='m1 time used'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m2_a_time_used',
            field=models.DurationField(default=datetime.timedelta(0, 21600), verbose_name='m2_a time used'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m2_b_time_used',
            field=models.DurationField(default=datetime.timedelta(0, 21600), verbose_name='m2_b time used'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m3_time_used',
            field=models.DurationField(default=datetime.timedelta(0, 9000), verbose_name='m3 time used'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m4_time_used',
            field=models.DurationField(default=datetime.timedelta(0, 9000), verbose_name='m4 time used'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m5_time_used',
            field=models.DurationField(default=datetime.timedelta(0, 43200), verbose_name='m5 time used'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m6_time_used',
            field=models.DurationField(default=datetime.timedelta(0, 10800), verbose_name='m6 time used'),
        ),
    ]
