# Generated by Django 3.0.6 on 2020-05-25 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200523_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audios', models.FileField(upload_to='audios/')),
                ('inspector', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Inspector')),
            ],
        ),
    ]
