# Generated by Django 3.0.6 on 2020-05-25 12:03

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_translatedaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='m2_b_audio1',
            field=models.FileField(default='/game/audio/CorruptedAudioChinese.mp3', upload_to=home.models.audio_upload_path),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m2_b_audio2',
            field=models.FileField(default='/game/audio/CorruptedAudioChinese.mp3', upload_to=home.models.audio_upload_path),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m2_b_audio3',
            field=models.FileField(default='/game/audio/CorruptedAudioChinese.mp3', upload_to=home.models.audio_upload_path),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m2_b_audio4',
            field=models.FileField(default='/game/audio/CorruptedAudioChinese.mp3', upload_to=home.models.audio_upload_path),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m2_b_audio5',
            field=models.FileField(default='/game/audio/CorruptedAudioChinese.mp3', upload_to=home.models.audio_upload_path),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m2_b_audio6',
            field=models.FileField(default='/game/audio/CorruptedAudioChinese.mp3', upload_to=home.models.audio_upload_path),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m2_b_audio7',
            field=models.FileField(default='/game/audio/CorruptedAudioChinese.mp3', upload_to=home.models.audio_upload_path),
        ),
        migrations.AddField(
            model_name='inspector',
            name='m2_b_audio8',
            field=models.FileField(default='/game/audio/CorruptedAudioChinese.mp3', upload_to=home.models.audio_upload_path),
        ),
    ]
