# Generated by Django 3.0.6 on 2020-05-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='ranking_switcher',
            field=models.BooleanField(default=False, verbose_name='ranking turn on/off'),
        ),
    ]
