# Generated by Django 3.0.5 on 2020-05-08 00:56

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_chi', models.CharField(default='输入联络人名字', max_length=200)),
                ('name_eng', models.CharField(default='Insert English Name Here.', max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RulesAndRegulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_chi', models.TextField(default='输入游戏规则', unique=True)),
                ('rule_eng', models.TextField(default='Insert Rules Here.', unique=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
            ],
        ),
    ]
